export const citiesPopulation = [{
    name: '2015',
    items: [{
      value: 21324000,
      name: 'Angular',
      country: 'Web/App'
    }, {
      value: 9735000,
      name: 'React',
      country: 'Web/App'
    }, {
      value: 9278441,
      name: 'JSP',
      country: 'Web/App'
    }]
  }, {
    name: '2016',
    items: [{
      value: 24256800,
      name: 'PHP',
      country: 'Web/Server'
    }, {
      value: 23500000,
      name: 'React',
      country: 'Web/App'
    }, {
      value: 21516000,
      name: 'Vue',
      country: 'Web/App'
    }, {
      value: 16787941,
      name: 'Angular',
      country: 'Web/App'
    }, {
      value: 15200000,
      name: 'HTML5',
      country: 'Web'
    }]
  }, {
    name: '2017',
    items: [{
      value: 4840600,
      name: 'JSP',
      country: 'Web/Server'
    }, {
      value: 4440000,
      name: 'HTML5',
      country: 'Web'
    }]
  }, {
    name: '2018',
    items: [{
      value: 14160467,
      name: 'Vue',
      country: 'Web/App'
    }, {
      value: 12197596,
      name: 'React',
      country: 'Web/App'
    }, {
      value: 8538689,
      name: 'JSP',
      country: 'Web/Server'
    }, {
      value: 5191690,
      name: 'Angular',
      country: 'Web/App'
    }, {
      value: 4470800,
      name: 'HTML5',
      country: 'Web'
    }, {
      value: 3517424,
      name: 'CSS',
      country: 'Web'
    }]
  }, {
    name: '2019',
    items: [{
      value: 8874724,
      name: 'Vue',
      country: 'Web/App',
    }, {
      value: 8550405,
      name: 'React',
      country: 'Web/App',
    }, {
      value: 3884307,
      name: 'JSP',
      country: 'Web/Server',
    }, {
      value: 2808503,
      name: 'Angular',
      country: 'Web/App',
    }]
  }, {
    name: '2020',
    items: [{
      value: 11895893,
      name: 'Vue',
      country: 'Web/App',
    }, {
      value: 8693387,
      name: 'React',
      country: 'Web/App',
    }, {
      value: 7776845,
      name: 'JSP',
      country: 'Web/Server',
    }, {
      value: 6429923,
      name: 'Angular',
      country: 'Web/App',
    }]
  }];
  