<template>
  <DxChart
    id="chart"
    :data-source="dataSource"
    title="2015~2020, Annual Language Usage Distribution Plot"
    @pointClick="onPointClick"
  >
    <DxCommonSeriesSettings
      argument-field="state"
      type="bar"
      hover-mode="allArgumentPoints"
      selection-mode="allArgumentPoints"
    >
      <DxLabel :visible="true">
        <DxFormat
          :precision="0"
          type="fixedPoint"
        />
      </DxLabel>
    </DxCommonSeriesSettings>
    <DxSeries
      value-field="react"
      name="react"
    />
    <DxSeries
      value-field="vue"
      name="vue"
    />
    <DxSeries
      value-field="html5"
      name="html5"
    />
    <DxSeries
      value-field="css"
      name="css"
    />
    <DxSeries
      value-field="php"
      name="php"
    />
    <DxSeries
      value-field="scss"
      name="scss"
    />
    <DxSeries
      value-field="ruby"
      name="ruby"
    />
    <DxSeries
      value-field="spring"
      name="spring"
    />
    <DxSeries
      value-field="django"
      name="django"
    />
    <DxSeries
      value-field="javascript"
      name="javascript"
    />
    <DxSeries
      value-field="cgi"
      name="cgi"
    />
    <DxSeries
      value-field="asp.net"
      name="asp.net"
    />
    <DxSeries
      value-field="jsp"
      name="jsp"
    />
    <DxSeries
      value-field="python"
      name="python"
    />
    <DxSeries
      value-field="xml"
      name="xml"
    />
    <DxSeries
      value-field="vrml"
      name="vrml"
    />
    <DxSeries
      value-field="wml"
      name="wml"
    />
    <DxSeries
      value-field="perl"
      name="perl"
    />
    <DxSeries
      value-field="sgml"
      name="sgml"
    />
    <DxSeries
      value-field="java"
      name="java"
    />
    <DxSeries
      value-field="c"
      name="c"
    />
    <DxSeries
      value-field="c++"
      name="c++"
    />
    <DxSeries
      value-field="c#"
      name="c#"
    />
    <DxSeries
      value-field="assembler"
      name="assembler"
    />
    <DxSeries
      value-field="lua"
      name="lua"
    />
    <DxSeries
      value-field="googleGo"
      name="googleGo"
    />
    <DxSeries
      value-field="r"
      name="r"
    />
    <DxSeries
      value-field="swift"
      name="swift"
    />
    <DxSeries
      value-field="rust"
      name="rust"
    />
    <DxSeries
      value-field="ajax"
      name="ajax"
    />
    <DxSeries
      value-field="sql"
      name="sql"
    />
    <DxSeries
      value-field="matlab"
      name="matlab"
    />
    <DxSeries
      value-field="mysql"
      name="mysql"
    />
    <DxSeries
      value-field="R"
      name="R"
    />
    <DxSeries
      value-field="rShiny"
      name="rShiny"
    />
    <DxSeries
      value-field="node.js"
      name="node.js"
    />
    <DxSeries
      value-field="typescript"
      name="typescript"
    />
    <DxSeries
      value-field="android"
      name="android"
    />
    <DxSeries
      value-field="c"
      name="c"
    />
    <DxSeries
      value-field="shellRsc"
      name="shellRsc"
    />
    <DxSeries
      value-field="make"
      name="make"
    />
    <DxSeries
      value-field="d"
      name="d"
    />
    <DxSeries
      value-field="c#"
      name="c#"
    />
    <DxSeries
      value-field="lisp"
      name="lisp"
    />
    <DxSeries
      value-field="prolog"
      name="prolog"
    />
    <DxSeries
      value-field="julia"
      name="julia"
    />
    <DxSeries
      value-field="shellScript"
      name="shellScript"
    />
    <DxSeries
      value-field="solidity"
      name="solidity"
    />
    <DxSeries
      value-field="ironPython"
      name="ironPython"
    />
    <DxSeries
      value-field="boo"
      name="boo"
    />
    <DxSeries
      value-field="lua"
      name="lua"
    />
    <DxSeries
      value-field="pl"
      name="pl"
    />
    <DxSeries
      value-field="JDBC"
      name="JDBC"
    />
    <DxSeries
      value-field="ODBC"
      name="ODBC"
    />
    <DxSeries
      value-field="rails"
      name="rails"
    />
    <DxSeries
      value-field="javaRsc"
      name="javaRsc"
    />
    <DxLegend
      vertical-alignment="bottom"
      horizontal-alignment="center"
    />
    <DxExport :enabled="true"/>
  </DxChart>
</template>
<script>
import {
  DxChart,
  DxSeries,
  DxCommonSeriesSettings,
  DxLabel,
  DxFormat,
  DxLegend,
  DxExport
} from 'devextreme-vue/chart';
//import { grossProductData } from './data.js';

export default {
  components: {
    DxChart,
    DxSeries,
    DxCommonSeriesSettings,
    DxLabel,
    DxFormat,
    DxLegend,
    DxExport
  },
  data() {
    return {
      //dataSource: grossProductData
      dataSource : this.$store.state.category_advanced
    };
  },
  methods: {
    onPointClick({ target }) {
      target.select();
    }
  }
};
</script>
<style>
#chart {
    height: 840px;
}
</style>
